// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFEiKpBAYDz3M7yO8zYnXS1DkrYlRt6Qw',
    appId: '1:874933875749:web:74238f5c4718c42504bbcc',
    messagingSenderId: '874933875749',
    projectId: 'aivellum-3521b',
    authDomain: 'aivellum-3521b.firebaseapp.com',
    storageBucket: 'aivellum-3521b.firebasestorage.app',
    measurementId: 'G-DJJ47LXSE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZIGlROgRbrRHG-tIqGrzXuYogVkglSUo',
    appId: '1:874933875749:android:992b9b692f5233fd04bbcc',
    messagingSenderId: '874933875749',
    projectId: 'aivellum-3521b',
    storageBucket: 'aivellum-3521b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYSED_qrJ_yUvMrOC9OiL74nJFBLEISs0',
    appId: '1:874933875749:ios:f5e19d6c8add28fb04bbcc',
    messagingSenderId: '874933875749',
    projectId: 'aivellum-3521b',
    storageBucket: 'aivellum-3521b.firebasestorage.app',
    iosBundleId: 'com.example.aivellum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYSED_qrJ_yUvMrOC9OiL74nJFBLEISs0',
    appId: '1:874933875749:ios:f5e19d6c8add28fb04bbcc',
    messagingSenderId: '874933875749',
    projectId: 'aivellum-3521b',
    storageBucket: 'aivellum-3521b.firebasestorage.app',
    iosBundleId: 'com.example.aivellum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFEiKpBAYDz3M7yO8zYnXS1DkrYlRt6Qw',
    appId: '1:874933875749:web:011d957f8062699f04bbcc',
    messagingSenderId: '874933875749',
    projectId: 'aivellum-3521b',
    authDomain: 'aivellum-3521b.firebaseapp.com',
    storageBucket: 'aivellum-3521b.firebasestorage.app',
    measurementId: 'G-T6NQ4FCGEE',
  );
}
